config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "/about" ,to:"pages#about"
  get "/help", to:"pages#help"

  resources :firstapps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firstapp.rb
class Firstapp < ApplicationRecord
	validates :name, presence:  true
	validates :department, presence: true
	validates :company, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def hello
		render plain: "helloworld"
	end
end

app/controllers/firstapps_controller.rb
class FirstappsController < ApplicationController
	before_action :set_find, only: [:edit, :update, :show, :destroy]
	def new
		@firstapp= Firstapp.new
	end

	def create
		@firstapp = Firstapp.new(firstapp_params)
		if @firstapp.save
			flash[:notice] = "Your Post is success"
			redirect_to firstapp_path(@firstapp)
		else
			render 'new'
		end
	end
	def show
		
	end

	def edit
		
	end

	def update
			if @firstapp.update(firstapp_params)
			flash[:notice] = "Your post is updated successfully"
			redirect_to firstapp_path(@firstapp)
		else
			render 'edit'
		end
	end
	def index
		@firstappsmany = Firstapp.all

	end

	def destroy
		@firstapp.destroy
		flash[:notice] = "Data was deleted successfully"
		redirect_to firstapps_path 
	end

	private
		def set_find
			@firstapp = Firstapp.find(params[:id])
		end
		def firstapp_params
			params.require(:firstapp).permit(:name, :department, :company)
		end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
	def home

	end

	def about

	end

	def help

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/firstapps/_formeditnew.html.erb
<% if @firstapp.errors.any? %>
<h2> The following errors prevented the database to store </h2>
<ul>
	<% @firstapp.errors.full_messages.each do |dis| %>
	<li><%= dis %></li>
	<% end %>
</ul>
<% end %>
<%= form_for @firstapp do |f| %>
<p>
	<%= f.label :Name %><br>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :Department %><br>
	<%= f.text_field :department %>
</p>
<p>
	<%= f.label :Company %><br>
	<%= f.text_field :company %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>
<p>
	<%= link_to "Back to list index", firstapps_path %>
</p>

app/views/firstapps/edit.html.erb
<h1> you are in edit page</h1>

<%= render 'formeditnew' %>

app/views/firstapps/index.html.erb
<h1>Listing all todos</h1>
<p>
	<%= link_to "Create new", new_firstapp_path %>
</p>
<table>
	<tr>
		<th>Name</th>
		<th>Department</th>
		<th>Company</th>
	</tr>

	<% @firstappsmany.each do |list| %>
	<tr>
		<td><%= list.name %></td>
		<td><%= list.department %></td>
		<td><%= list.company %></td>
		<td><%= link_to "Edit", edit_firstapp_path(list) %></td>
		<td><%= link_to "Show", firstapp_path(list) %></td>
		<td><%= link_to "Delete", firstapp_path(list), method: :delete, data: {confirm: "Are you sure?"} %></td> 
	</tr>
	<% end %>
</table>

app/views/firstapps/new.html.erb
<h1>New page</h1>
<%= render 'formeditnew' %>

app/views/firstapps/show.html.erb
<h1>Show page</h1>
<p>
	Name: <%= @firstapp.name %>
</p>
<p>
	Department: <%= @firstapp.department %>
</p>
<p>
	Company: <%= @firstapp.company %>
</p>
<p>
	<%= link_to "Edit this show", edit_firstapp_path(@firstapp) %>
	<%= link_to "Back to list index", firstapps_path %>

</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
     <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>You are in about page</h1>

app/views/pages/help.html.erb
<h1>You are in Help page</h1>
<h2>Enter your queries here</h2>

app/views/pages/home.html.erb
<h1>hi</h1>